/* Generated By:JavaCC: Do not edit this line. DfmParserConstants.java */
/*
 * The MIT License
 *
 * Copyright 2014 Krzysztof Kaszkowiak.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package eu.kaszkowiak.jdfm.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DfmParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING_SQ = 4;
  /** RegularExpression Id. */
  int BRACKETS = 7;
  /** RegularExpression Id. */
  int WHITESPACE = 8;
  /** RegularExpression Id. */
  int OBJECT = 9;
  /** RegularExpression Id. */
  int ITEM = 10;
  /** RegularExpression Id. */
  int END = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int HASH_STRING = 13;
  /** RegularExpression Id. */
  int ENDLINE = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int CROC_PAREN_L = 17;
  /** RegularExpression Id. */
  int CROC_PAREN_R = 18;
  /** RegularExpression Id. */
  int PAREN_L = 19;
  /** RegularExpression Id. */
  int PAREN_R = 20;
  /** RegularExpression Id. */
  int CURLY_BRACKET_L = 21;
  /** RegularExpression Id. */
  int CURLY_BRACKET_R = 22;
  /** RegularExpression Id. */
  int PLUS_SIGN = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING_SQ = 1;
  /** Lexical state. */
  int IN_BRACKETS = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\'\"",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"\\\'\"",
    "\"[\"",
    "<token of kind 6>",
    "\"]\"",
    "<WHITESPACE>",
    "\"object\"",
    "\"item\"",
    "\"end\"",
    "<IDENTIFIER>",
    "<HASH_STRING>",
    "<ENDLINE>",
    "\"=\"",
    "\":\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
  };

}
