/* Generated By:JavaCC: Do not edit this line. DfmParserConstants.java */
package eu.kaszkowiak.jdfm.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DfmParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING_SQ = 4;
  /** RegularExpression Id. */
  int BRACKETS = 7;
  /** RegularExpression Id. */
  int KW_BRACKETS = 10;
  /** RegularExpression Id. */
  int WHITESPACE = 11;
  /** RegularExpression Id. */
  int OBJECT = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int ENDLINE = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING_SQ = 1;
  /** Lexical state. */
  int IN_BRACKETS = 2;
  /** Lexical state. */
  int IN_KW_BRACKETS = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\'\"",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"\\\'\"",
    "\"(\"",
    "<token of kind 6>",
    "\")\"",
    "\"[\"",
    "<token of kind 9>",
    "\"]\"",
    "<WHITESPACE>",
    "\"object\"",
    "\"end\"",
    "\":\"",
    "<ENDLINE>",
    "\"=\"",
    "<IDENTIFIER>",
  };

}
